- name: "Docker-Webserver"
  hosts: task10
  tasks:
    - name: "repository for docker"
      yum_repository:
        name: "docker"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        description: "docker repo"
        gpgcheck: no
        enabled: yes
        state: present
    - name: "installing docker api"
      command: "pip3 install docker"
    - name: "installing docker-ce"
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present
    - name: "starting docker services"
      service:
        name: "docker"
        state: started
        enabled: yes
    - name: "directory for webserver files"
      file:
        path: "/webserver"
        state: directory
    - name: "copying file to webserver directory"
      copy:
        src: "/root/task10.html"
        dest: "/webserver"
    - name: "pulling image of httpd from docker hub"
      docker_image:
        name: "httpd"
        source: pull
    - name: "launching docker container" 
      docker_container:
        name: "Webserver"
        image: "httpd:latest"
        pull: yes
        exposed_ports:
          - "800"
        ports:
          - "800:80"
        volumes:
          - "/webserver:/usr/local/apache2/htdocs"
